server:
  port: 8082
spring:
  application:
    name: service-oss

#logging:
#  level:
#    root: debug

# ali nacos 配置
nacos:
  config:
    server-addr: 127.0.0.1:8848
  discovery:
    server-addr: 127.0.0.1:8848

# aliyun OSS 配置
aliyun:
  oss:
    file:
      endpoint: https://oss-cn-hangzhou.aliyuncs.com
      accessKeyId: TFRBSTV0NXlyRUFFQ0t0dEFzMVd5Q0R0
      accessKeySecret: UWFjdGZpQmVuempiVmFQWGNVYTRMa0NNbzNJMHQ5
      bucketName: badfox
      count: 3
      outTime: 1000 #ms



