server:
  port: 8082
spring:
  application:
    name: service-oss

#logging:
#  level:
#    root: debug

aliyun:
  oss:
    file:
      endpoint: https://oss-cn-hangzhou.aliyuncs.com
      accessKeyId: TFRBSTV0NXlyRUFFQ0t0dEFzMVd5Q0R0
      accessKeySecret: UWFjdGZpQmVuempiVmFQWGNVYTRMa0NNbzNJMHQ5
      bucketName: badfox
      count: 3
      outTime: 1000 #ms



